matrix:
  include:
    - language: python
      sudo: true
      dist: trusty
      python: 3.5
      before_script:
        - curl -s https://install.zerotier.com/ | sudo bash
      script:
        - bash tests/performance/travis_script.sh
