matrix:
  include:
    - language: python
      sudo: true
      dist: trusty
      python: 3.5
      before_script:
        - sudo apt update
        - sudo apt install sshpass
        - curl -s https://install.zerotier.com/ | sudo bash
      script:
        - sshpass -p ${PERF_CTRL_PASS} ssh -tA ${PERF_CTRL_UN}@${PERF_CTRL_IP} ls
