matrix:
  include:
    - language: python
      sudo: true
      dist: trusty
      python: 3.5
      before_script:
        - sudo apt update
        - sudo apt install sshpass
        - curl -s https://install.zerotier.com/ | sudo bash
      script:
        - bash tests/performance/travis_script.sh
        - ping -w5 $PERF_CTRL_IP
        - sleep 30
        - sudo sshpass -p "$PERF_CTRL_PASS" ssh -oStrictHostKeyChecking=no $PERF_CTRL_UN@$PERF_CTRL_IP 'ls'
